### ISSUE TITLE
Merge box art option in the settings and add a new one. 

### ISSUE THREAD

**Issue by NightScript370** [DS-Homebrew/TWiLightMenu#1007]
**Is your feature request related to a problem? Please describe.**
There are two separate entries for box art options. One is to show them and one is to cache them.

**Describe the solution you'd like**
We could merge the options to have "No Box Arts", "No Cache", "Cache Box Art", "hybrid cache"

Hybrid would be it caches when you hover over it, as opposed to no caches not caching it at all and caching causing a huge lag when opening it.

**Additional context**
Maybe there could be a migrator of sorts in the CIA/boot.nds

**Comment by NightYoshi370** [comment]
I think @Evie did the merge, so now all that's left is the hybrid cache.

**Comment by Epicpkmn11** [comment]
I was going to add the hybrid mode, but honestly is the caching worth having? I can't tell any difference between it on or off since both happen in like a 10th of a second but having it on makes the folder load take over a second longer... So its using 1.8MB of RAM and a fairly long time on load for a tiny fraction of a second of speed when selecting a game...

**Comment by NightYoshi370** [comment]
I remember having lag when scrolling through my ROM list with it off. Although, that might not be an issue anymore if we switch to libslim

**Comment by Epicpkmn11** [comment]
That can't be related to boxart as boxart isn't loaded until you stop scrolling, it just clears the boxart when you start and draws the last one when you stop... Even spamming the key instead of holding so it does draw the boxart I can't feel a difference so I think its the key repeat not the boxart that it takes a bit between loads...

Maybe in an older version it drew the boxart every app? In the current I don't really see a reason for the caching though...

**Comment by NightScript370** [comment]
Superceeded by #2060
