### ISSUE TITLE
Text wrapping on german loading screens

### ISSUE THREAD

**Issue by sjmller** [DS-Homebrew/TWiLightMenu#1018]
**Your console configuration:** DSi with HiyaCFW + Unlaunch
**TWiLight Menu++ Version:** v14.2.0
**TWiLight Menu++ Theme:** DSi, 3DS, Sega Saturn

### Expected behaviour

Centered and wrapped text inside the loading screens, as it is the case for the english language. 

### Actual behaviour

The text is not wrapped and some letters are cut off. Besides the text wrapping the umlaute #995 are missing. 

### Steps to reproduce

1. Change Language to German
2. Switch back to game selection

**Comment by Epicpkmn11** [comment]
I marked the strings as having issues on [the Crowdin](https://crowdin.com/project/TwilightMenu), I didn't adjust them myself as I'd rather leave it to someone who knows German to decide where the newlines should go since I'm not sure where works best, if anyone wants to post suggestions here that works too. A third line can be added if balancing out the two lines doesn't work, though it would probably be ideal to keep it to two lines.

**Comment by Epicpkmn11** [comment]
Just checked Crowdin, these have all been fixed so this should be able to be closed
