### ISSUE TITLE
Cheats and MD5 Checksum

### ISSUE THREAD

**Issue by RizeYuzuki** [DS-Homebrew/TWiLightMenu#1045]
**Is your feature request related to a problem? Please describe.**
The cheat feature uses MD5 Checksum in order to give the corresponding cheats for a specific game. Making it impossible to use with RomHacks, Randomized games or slightly altered games even though it should be working. The menu does recognize a altered / randomized game with the correct title, just not the cheat feature.

**Describe the solution you'd like**
Getting the cheat codes according to the game title, not the MD5. I am aware that this might cause conflict depending on the game's region (U/PAL/J). So I was thinking of when you enable the cheat code list, you will be prompted to select your game's region first and then have it fetch the corresponding cheats.

**Describe alternatives you've considered**
I also wouldn't mind fetching the codes by manually choosing my game through a list sorted alphabetically just so I don't have to open up my console and use a PC emulator every time I want to use a cheat.

**Additional context**
I altered my game to make text boxes appear immediately and this was enough to not being able to use any cheats since it changed the MD5.
Same thing happened with randomized games.

**Comment by Epicpkmn11** [comment]
Personally I don't think this would be a good idea since you can easily just open the database in r4cce and change the checksum to match your rom if you need, and most of the time this doesn't provide much benefit at the cost of increased confusion from the several different versions of the same game which may or may not have the same codes, especially for games like Pokémon where iirc DSJ's database has a lot of rom hacks already.

Also it uses a CRC32 of the header, not an MD5 fyi

**Comment by unresolvedsymbol** [comment]
This would also break trimmed ROMs :-1: from me
