### ISSUE TITLE
Bring Back GBARunner Booter

### ISSUE THREAD

**Issue by RinMaru** [DS-Homebrew/TWiLightMenu#1162]
**Describe the solution you'd like**
The only way to get into GBARunner is Navigating to the _GBA folder and launching a game is but it would be nice to just have an icon to boot it like in the other themes in the DSI Theme

**Comment by NightYoshi370** [comment]
Why have GBARunner2 get special treatment? It's much easier to just launch it from the actual menu itself.
There's no reason to go back.

**Comment by SleepyLark** [comment]
You don't need to open it from the _gba folder.  If you're on the latest version you can boot the .gba rom from anywhere through Twilight Menu like you can with any other game, it's actually easier than before

**Comment by DraconicNEO** [comment]
> 
> 
> Why have GBARunner2 get special treatment? It's much easier to just launch it from the actual menu itself.
> There's no reason to go back.

Maybe because it's Included in the classic screen.
![twilight-menu-3ds](https://user-images.githubusercontent.com/44508470/124715445-04809980-ded1-11eb-8d17-7c0ed9e64449.jpg)

I mean why include it in the classic screen if we're going to treat it like any other emulator?

**Comment by RocketRobz** [comment]
> > Why have GBARunner2 get special treatment? It's much easier to just launch it from the actual menu itself.
> > There's no reason to go back.
> 
> Maybe because it's Included in the classic screen.
> ![twilight-menu-3ds](https://user-images.githubusercontent.com/44508470/124715445-04809980-ded1-11eb-8d17-7c0ed9e64449.jpg)
> 
> I mean why include it in the classic screen if we're going to treat it like any other emulator?

It's been gone from it for a while now.

**Comment by Kaisaan** [comment]
From what I know, it was there on the classic menu (and also available in the other themes) because GBA titles couldn't be launched directly. But that issue is gone now, you can just launch GBA titles directly from TWiLight Menu++ and GBARunner2 will work as intended. So there isn't any need to still have it on these themes in the later versions. Only reason why you still see it on your classic menu is because you haven't updated. I recommend updating to the latest release. You can find update guides [here](https://wiki.ds-homebrew.com/twilightmenu/updating).
