### ISSUE TITLE
Twilightmenu is Unresponsive with 3DS Theme

### ISSUE THREAD

**Issue by Someguy1519** [DS-Homebrew/TWiLightMenu#1180]
**Your console configuration:**
New 3DS XL 11.13.0-45U Luma3DS 10.2
**TWiLight Menu++ Version:** 16.2.0
**TWiLight Menu++ Theme:**
3DS

### Expected behaviour

Able to scroll through menus and select games.

### Actual behaviour

No response at all from any button presses or touch screen taps

### Steps to reproduce

1. Load up Twilightmenu with 3DS Theme
2. Press any button or touch anything on the touch screen
3.

**Comment by Dhalian** [comment]
I met the same problem to fix it it's quite simple : press ON then almost instantly after on START then select GodMode9 , once on GM9 go to ``SD://_nds/TWiLightMenu`` , delete ``settings.ini`` , restart the TWiLightMenu , now reconfigure it as before but by selecting another theme , but don't use the 3DS theme if you don't want to meet this problem again

**Comment by NightYoshi370** [comment]
@Dhalian That doesn't fix the issue though. The 3DS theme not working is an issue, and switching to another theme isn't a fix

Also, the method that you use is quite harmful. You're suggesting to throw away the entire settings just because of a theme variable, which is wrong. Not to mention, the method you use assume that it must be done through GodMode9 and assumes that they already have the Luma 10.2 + GodMode9 workaround, which is quite a complicated setup.

Due to this, I am required to hide (but not delete cause that would be censorship) your comment.

**Comment by Dhalian** [comment]
Yes I understand ,if I'm wrong about anything in the future there's no problem for messages to be deleted.

**Comment by NightYoshi370** [comment]
Nah, I'd rather not censor you, especially considering that it does *work*. It's just not ideal.
I only censor irrelevant comments or flat out memes.

**Comment by Dhalian** [comment]
Okay

**Comment by Dhalian** [comment]
So is there finally a solution to this problem?

**Comment by MarceloZeri** [comment]
I hope there's a solution. I always used this theme with no problem. And recently I was enjoying the game cover arts, which only show in this theme.

**Comment by NightYoshi370** [comment]
Fixed in v16.2.1

**Comment by Someguy1519** [comment]
The 3DS Theme is once again unresponsive on the a57d0f69 build. The DSi theme seems to randomly freeze when scrolling.

**Comment by RocketRobz** [comment]
Fixed in v16.2.2
