### ISSUE TITLE
DSi theme sometimes freezes on flashcards in DS mode

### ISSUE THREAD

**Issue by RocketRobz** [DS-Homebrew/TWiLightMenu#1231]
**Your console configuration:** DS Phat and DS lite
**TWiLight Menu++ Version:** ???
**TWiLight Menu++ Theme:** DSi

### Expected behaviour

DSi theme should function without freezes.

### Actual behaviour

DSi theme becomes unresponsive, and the music freezes.

### Steps to reproduce

1. Launch TWiLight Menu++ on your flashcard.
2. Make sure theme is set to `Nintendo DSi` in TWLMenu++ Settings.
3. Exit TWLMenu++ Settings.
4. Scroll through the list, if you haven't gotten the freeze yet.

**Comment by Lv44EnderShaman** [comment]
I've been getting this exact freeze for a while now. At first, I thought it was because of the flashcart I was using, a DSTTi, not having the right files for YSMenu on it; after checking to make sure all files were genuine and up to date, making sure none of the files were hidden on the flashcart as well, I kept running into the same issue. It's a genuine cart, and there's no problems with the MicroSD. At this point, I'm wondering if it might be a libfat issue or something similar...
