### ISSUE TITLE
Korean menu game's titles

### ISSUE THREAD

**Issue by poketony** [DS-Homebrew/TWiLightMenu#1264]
![KakaoTalk_20201221_202855351](https://user-images.githubusercontent.com/57011422/102772727-58131600-43cb-11eb-9b7e-84db0f26b4ab.jpg)

font table is incomplete. 
ROM titles have to show '호텔 더스크의 비밀', but menu show '호? 더스크의 비?'. 
many korean characters are lost in font table.

**Comment by Epicpkmn11** [comment]
Do you know of any good lists of all the Korean DS game titles? The fonts are kept limited to just what's necessary because of RAM issues, but I can add all of the hangul syllable blocks used in retail games if that doesn't cause issues... If it does maybe we could start having a more limited font for DS mode and a more complete one for DSi mode.

**Comment by poketony** [comment]
[korean ds game list.txt](https://github.com/DS-Homebrew/TWiLightMenu/files/5729899/korean.ds.game.list.txt)

Here.
