### ISSUE TITLE
NDS Cheats supports Chinese display request

### ISSUE THREAD

**Issue by cyaomushen** [DS-Homebrew/TWiLightMenu#1269]
![3a7fa186-6f06-4864-a561-cb2071959179](https://user-images.githubusercontent.com/36250382/103060725-21fcae80-45e4-11eb-89bb-c2aa021802a9.jpg)
![388d8395-5b65-4d08-a620-5d40f4911c37](https://user-images.githubusercontent.com/36250382/103060730-25903580-45e4-11eb-98e5-39bd0d4d5e42.jpg)

NDS Cheats supports Chinese display request.

**Comment by RocketRobz** [comment]
The remaining Chinese characters would have to be implemented.
Currently, only the required characters for game titles and Chinese-translated text are implemented.

**Comment by Epicpkmn11** [comment]
If you add these nftr files to the theme your using then it should fix it [CJK_with_Nintendo_NTLG.zip](https://github.com/DS-Homebrew/TWiLightMenu/files/5561320/CJK_with_Nintendo_NTLG.zip) (these are from another issue on the topic and have most CJK characters in them)

I've got an idea on how to fix this properly so I might do that soon, but for now adding these to the theme works.

(`sd:/_nds/TWiLightMenu/dsimenu/themes/dark/font/(large|small).nftr` (create the font folder))

**Comment by Epicpkmn11** [comment]
I've marked this as fixed by #1287, but it might still be missing some characters as I only added the most common few thousand + the iQue font + some from fan translation titles from another issue + a few more probably, but if there are still any missing after that please reopen this and let me know where I can find good lists of chinese characters to add.
