### ISSUE TITLE
CHEATS

### ISSUE THREAD

**Issue by Kevin-zhao-kz** [DS-Homebrew/TWiLightMenu#1315]
Hello, is there any way for cheats to support real Chinese

**Comment by Epicpkmn11** [comment]
Are you on the latest version? (v18.2.1)

The fonts were reworked a bit and expanded recently so now when running in DSi Mode (or from flashcards with a memory expansion pak) it should now have a pretty complete font for Chinese, and on flashcard you can change Settings -> Font to `Chinese (Simplified)` instead of `Default` to get most of them too, at least for Simplified Chinese, I didn't make a special one for Traditional Chinese yet since I need a good list of characters to include that's under ~7000 or so

**Comment by Epicpkmn11** [comment]
I'm going to assume that fixed it by the lack of a response and close this. Feel free to reopen if that didn't fix it.

**Comment by NightYoshi370** [comment]
I think they mean a cheat listing in chinese, which wouldn't be a twilight issue so yeah, closing is fine. 👍
