### ISSUE TITLE
Support Wood R4 savefile convention

### ISSUE THREAD

**Issue by robinei** [DS-Homebrew/TWiLightMenu#1378]
I want to be able to move an SD card between my R4 and the SD card slot on my DSi (so I can play on other DSes without hassle). 

The only thing stopping that now it that TWiLightMenu does not support storing the save side by side with the game using the `game.nds.sav` convention. I would be really happy if this was possible to optionally enable in settings.

**Comment by lifehackerhansol** [comment]
I'm not too sure how useful this will be. The _only_ kernel that does `.nds.sav` is Wood. ~~honestly that naming convention is a mistake~~

You can actually change Wood's settings to use `.sav` instead, which won't convert your existing saves to `.sav` but it will load from that extension in the future. Why that is not the default, I'm not sure, but here we are. Maybe you should set it that way, and change all the extensions accordingly, so this won't be an issue in the future.

**Comment by DraconicNEO** [comment]
As @lifehackerhansol said I don't think it's reasonable to add support for something that isn't used in the majority of situations. Since the Majority of Kernels don't support `.nds.sav` it seems like it would cause more harm and confusion than it would help people. Really you're better off just switching over to using `.sav` on Wood (I think you can just rename saves from `.nds.sav` to `.sav` but don't quote me on that since I've never used that convention).

**Comment by lifehackerhansol** [comment]
You can and it works (and it should be that way by default but oh well.)

Closing issue, as we described above.
