### ISSUE TITLE
"Unban" button

### ISSUE THREAD

**Issue by gek169** [DS-Homebrew/TWiLightMenu#1379]
Problem:
Shit moderators banned me while I was AFK for some shit

Solution:
A button for unbanning yourself from the discord server to fix the shitty situation

Alternates i've considered:
Making alternate accounts? Too much work. 
Reporting the github to nintendo to get it DMCA'd? Against my best interests.
Writing this 

Context: 
I was away from the keyboard and apparently one of your dumb shit moderators banned my ass, probably because I said putting virtue signalling crap in your video games was a bad idea

this place is no better than the nintendork modding server and no wonder you've got all these pedophiles and shit

**Comment by RocketRobz** [comment]
Dear Gek,
Our staff team will not be unbanning you, due to a constant repeat of the actions that has lead up to your ban in the first place. You haven't demonstrated a will to improve yourself either, determined by the creation of this very issue. We do understand your frustrations, but this is not the proper way to go about it.

For one, rather than communicate with the staff through other methods (such as through Discord's direct messages or emailing one of the moderators), you have decided to publicize it in an irrelevant GitHub Repository. The TWiLight Menu++ GitHub Repository, as well as any other repository on the DS-Homebrew GitHub Organization, is not the place to post appeals.
This issue, however, is a great reference point to show why your behavior is wrong.

> "Shit moderators banned me while I was AFK for some shit"
> "this place is no better than the nintendork modding server and no wonder you've got all these pedophiles and shit"
> "one of your dumb shit moderators banned my ass, probably because I said putting virtue signalling crap in your video games was a bad idea"

Comments like these, are not necessary. You have repeatedly shown to be too vulgar despite our constant discouragement of this behavior.
Not only that, you failed to realize that it was a buildup of wrong actions, especially considering that incident was the second incident after Kaisaan gave you a final warning.

So which parts of your behavior is wrong? You have shown to:

- Disregard the feelings of others in terms of being homophobic, transophobic (twice) and being comfortable entertaining a spammer with more threats to add to his list.
- Made such threats yourself, such as in the GodMode9i situation where you wanted to stangle the dev and in this very issue ("Reporting the github to nintendo to get it DMCA'd? Against my best interests.", which is quite baseless. Good luck getting Nintendo to DMCA this repo when we have no copyrighted code in here)
- Bring in external drama for no reason

Many users were uncomfortable during your stay at our environment, yet we were patient and let you stay. However, our patience has pushed past the limit, and openly insulting lesbians was the final straw. The reason why we are unable to "stay neutral" or whatever may be expected of non-LGBTQ communities is that by acting safe to bigots, it makes those targetted feel unsafe leading to their departure. We have thus created a safe environment for bigotry, ruining our image.

As a word of advice, we are not the only internet community to act on the defensive side rather than let you rip right through our community members. You have encouraged violence in the Nintendo Homebrew server and insulted GitHub Projects for not meeting your expectations. Rather than constantly point fingers at others, maybe it's time to take a good look at the man in the mirror.

Your appeal is denied. For the next time you try to appeal, consider waiting a bit and emailing a moderator privately. NightScript (the one who originally banned you) is willing to give over his email to sort this out: NightYoshi370@outlook.com. As for me, well, just show me that you've changed and maybe I'll consider it.

Have a good day
~RocketRobz, main administrator of DS⁽ⁱ⁾ Mode Hacking

**Comment by Epicpkmn11** [comment]
Robz's post does a much better job expressing how we feel than anything I could write, but to show that we are unified in this decision and this isn't just some corrupt mod or so, I've written a ~~rambley mess~~ response too: https://gist.github.com/Epicpkmn11/89ef10c31cbc32b5a4fe8be90aba0bdc

**Comment by gek169** [comment]
I'm sending your project's page to Nintendo AP.
Enjoy the DMCA.

**Comment by NightYoshi370** [comment]
Your time will be wasted, because no outcome will come out of it.
However, you will no longer waste my time. Enjoy the block that will 100% happen (instead of the petty DMCA threat, which has no basis)
