### ISSUE TITLE
Boxart and Cheats download tool

### ISSUE THREAD

**Issue by syndenbock** [DS-Homebrew/TWiLightMenu#1405]
First of all I hope this place is fine to open the issue, I wanted to open it on the Twilight Menu Updater but that isn't possible as the repo has been archived.

**Is your feature request related to a problem? Please describe.**
With Twilight Menu Updater being discontinued, the tool for downloading box art and cheats effectively is discontinued aswell.

**Describe the solution you'd like**
I would like to have a small separate application for downloading box art and cheats just like the tool in the twilight menu updater. A universal-updater script would be even better, but I don't think that's realizable.

**Describe alternatives you've considered**
I will keep the Twilight Menu Updater installed to still have this tool available.

**Comment by SuperSaiyajinStackZ** [comment]
Universal-Updater can already download the `usrcheat.dat` with the `NDS Cheat Databases` entry.

For the boxarts, there is a fork of TWiLight Menu++ Updater, which is specifically for every type of boxarts: https://github.com/KirovAir/TWiLightMenu-Updater/releases.

**Comment by Mewthree3** [comment]
I just keep TWL updater at the version just before last to download boxarts, but the fork seems nice to use as well

**Comment by NightScript370** [comment]
I think an internal conclusion with Robz was already made (and if I'm incorrect, please correct me because this was a while ago) that TWiLight Menu++ would not be including any WiFi stuff:

- `usrcheat.dat` is currently over 40MB, which would take so long to download. The reason why Universal-Updater 3DS can download it so quickly is because it's in a 7z container, which wouldn't work on the DSi.
- Box-Art has no implementation in the Universal-Updater ecosystem but overall, has the problem of DSiWiFi being unusable with the TWiLight environment. Even if the connection issues got resolved, there's still the issue of an ARM7 binary not being able to contain both DSiWiFi **&** MaxMod (our current sound engine).

It's probably for the best it gets handled separately so that the scope of TWiLight is narrow.
Closing...
