### ISSUE TITLE
R4iTT does not boot via slot1launch on 3DS

### ISSUE THREAD

**Issue by AerGlass** [DS-Homebrew/TWiLightMenu#1519]
**Console Configuration:** New Nintendo 2DS XL with Luma3DS
 
**TWiLight Menu++ Version:*20.4.1* 
**TWiLight Menu++ Theme:*DSi* 

### Expected behaviour
be able of run it

be able to run the r4.
### Steps to reproduce

1.Run twilight menu ++
2.put you r4itt
3.run it

I was with a r4itt that are rare, it is a New r4itt 3ds, I also have and old r4itt that funtions correctly, the r4 is dead, for some reason ONLY twilight menu was able to register it, but when I run it...

![WIN_20210622_12_11_32_Pro](https://user-images.githubusercontent.com/86316669/122970095-126fdf80-d353-11eb-90db-7cc0150259a3.jpg)

This also hapens with the old r4itt that is good.

**Comment by lifehackerhansol** [comment]
Please take a picture of both R4iTTs and send it.

~~tbh none of the r4itts are actually that good~~

**Comment by TheCatHacker562** [comment]
![WIN_20210622_14_34_58_Pro](https://user-images.githubusercontent.com/86316669/122988195-1574cb00-d367-11eb-8734-1d661c2de1bb.jpg)

**Comment by lifehackerhansol** [comment]
They're quite old and generally not well supported that's why.

I have no idea what that left cart is, is it also a R4iTT 3DS NEW?

For the right one, is it working normally? (as in not TWiLight, but maybe Unlaunch or the DSi Menu)

**Comment by TheCatHacker562** [comment]
the one of the left is a old r4itt 
![imagen](https://user-images.githubusercontent.com/86316669/123181786-9c06d680-d453-11eb-8627-721226966150.png)
this one works. the other one doesn't
Both cards can't run via twilight menu++

**Comment by lifehackerhansol** [comment]
If it doesn't work normally, then of course it won't work with TWiLight. That's a given. ("normally" as in, it doesn't work on a DS/DS Lite, or it doesn't launch from the regular Slot-1 launcher on a hacked DSi/3DS)

Back to your one that works normally, the older R4iTT. Please update TWiLight Menu++ to the latest nightly and try it, then report back.

**Comment by TheCatHacker562** [comment]
still the same (tried with both)

**Comment by lifehackerhansol** [comment]
I kind of just remembered this issue. 

Do you have access to GodMode9? I wonder what the header of this cart is, and whether legacy mode might solve the boot issue.

**Comment by TheCatDev** [comment]
Yes, i have acess to godmode9

**Comment by lifehackerhansol** [comment]
Insert cart, load GodMode9, go to GAMECART, and extract the `.txt` file that is in it. Please do for both carts.
Upload them here, or some other place and link it here, please.

**Comment by TheCatDev** [comment]
I thinked that the new one was useless, its now in trash (since it didn't
work) i will upload the old one

**Comment by TheCatDev** [comment]
here is (the old one because the new one broke)
[STAR_WARS_LA_AWUP41_00.txt](https://github.com/DS-Homebrew/TWiLightMenu/files/7253767/STAR_WARS_LA_AWUP41_00.txt)

**Comment by lifehackerhansol** [comment]
First, update TWiLight Menu++ to the latest version, if you haven't already. There was a new release last night. Let me know if that works.

**Comment by TheCatDev** [comment]
Still, didn't work

**Comment by lifehackerhansol** [comment]
[slot1launch.zip](https://github.com/DS-Homebrew/TWiLightMenu/files/7254082/slot1launch.zip)

Download this, extract it, and replace it with the one inside the `_nds/TWiLightMenu/` folder. See if it works again.

**Comment by TheCatDev** [comment]
no, didn't work

**Comment by lifehackerhansol** [comment]
Can you take a clearer picture of the cart you have (both front and back) and send it here? I _think_ I actually have this cart myself, but I want to confirm before testing something else.

**Comment by TheCatDev** [comment]
![DSC00287](https://user-images.githubusercontent.com/86316669/135343290-c26a7fd2-a152-4c5b-96d9-6a89693de90f.JPG)
![DSC00285](https://user-images.githubusercontent.com/86316669/135343310-7038f017-c1ee-472a-acca-d240d6f45e94.JPG)
![DSC00286](https://user-images.githubusercontent.com/86316669/135343316-d23fdfed-b859-4109-91ff-eb4d9b95cf41.JPG)

**Comment by lifehackerhansol** [comment]
I definitely own this cart. I'll test on my end and see.

**Comment by lifehackerhansol** [comment]
After some testing, this issue is only found on the 3DS family consoles. I am able to boot it fine on a DSi through slot1launch. Which is interesting because Unlaunch doesn't like the cart at all.

**Comment by TheCatDev** [comment]
Interesting...

**Comment by dennyferrer** [comment]
i have the same issue in a dsi ver 1.3u with this cart and yes unlaunch dont read the card correctly
i have the latest twlmenu and latest unlaunch
the cart is working but doesnt boot trought twlmenu
![IMG_20211002_144515](https://user-images.githubusercontent.com/91897201/135870680-9bc352b7-0f17-4bcc-a2cf-a54651d2638f.jpg)
tested with this carts and same result black screen with 4 color squares

**Comment by lifehackerhansol** [comment]
@dennyferrer Your original R4 (left most one) not working is most likely a contact issue. I cannot reproduce the four squares on both my DSi nor 3DS. Perhaps blow into the slot and onto the R4 itself to check because that one boots from both TWiLight and Unlaunch for me (all three of mine do.)

The two on the right are both identical carts, and that's what we're trying to figure out here. Though TWiLight seems to launch it on a DSi, so not sure what is happening to you.

**Comment by dennyferrer** [comment]
ohh tanks the og r4 is working now i only clean the cart slot on the dsi but the r4itt gives me the same issue i think is a problem with the cart itself maybe a different revision of the cart i will try updating the firmware of the cart i hope that solve the problem

**Comment by lifehackerhansol** [comment]
I've tried updating the firmware on my own two R4iTTs and neither of them are working still, at least on my 3DS.

**Comment by dennyferrer** [comment]
i tried to update the cart firmware but its already updated so i make some research and i think its a comunication problem between the cart hardware and the ds because the og r4 i covered the contacts with a piece of paper and woala black screen with squares i remove the paper and its working fine tomorrow il test this with other dsi

**Comment by RocketRobz** [comment]
iirc, recent versions have fixed this issue.

@lifehackerhansol Can you confirm?

**Comment by lifehackerhansol** [comment]
> iirc, recent versions have fixed this issue.
> 
> @lifehackerhansol Can you confirm?

This has not been fixed. Evie and I tried to fix it and nothing came out of it. Still whitescreens.

**Comment by AerGlass** [comment]
it was fixed, idk when but my r4itt works now, my r4itt is like breaking (it sometimes does not work) but whatever

**Comment by AerGlass** [comment]
this broke? i mean i found another r4itt, launched it via twl++ and this problem ocurred again, tried my older r4itt which i normally use and this problem ocurred again

**Comment by AerGlass** [comment]
i may help with this but im the dumbest with the twl++ source code, my mind has expanded since 2021 however i do not want to mess with this code lol

**Comment by lifehackerhansol** [comment]
~~I don't either~~

Ultimately I think the slot1launch module just needs to be rewrote entirely. This cart isn't the only one to fail like this.

But that'll take a while, if it even happens.

**Comment by AerGlass** [comment]
in the latest twl ++ release (25.9.6) apart from the dsi menu change (which i like) now the squares are gone, bottom screen black, top screen white

**Comment by aerglass** [comment]
I got a new card because the SD Slot broke on my older one, I would have bought something else if there was stock but there wasn't so whatever.

This card, is the old R4iTT for 3DS with the screw on the back (purple and this time, it has the label), It works fine if I launch it via the 3DS menu, The first thing I did after setting up the cart with YSMenu was to run it with Twilight Menu++ and it worked, perfectly? I did remove the Micro SD card and got the white screen with no logo something that never happens. Maybe this is because I didn't upgrade the firmware which I won't do since there are no pros of doing it.

> it was fixed, idk when but my r4itt works now, my r4itt is like breaking (it sometimes does not work) but whatever

This was before the SD slot was major issues, afterwards the card started to be really unrealiable since the sd slot randomly stopped working midway normal operation. Now the SD slot doesn't work no matter what, It makes sense now.

I don't know if I should close this issue, I mean the card boots, It works fine. But the errors don't show up. Could this be some kind of problem later on?
