### ISSUE TITLE
Slot-1: Touch Mode - DSi Mode - Breaks touch and audio

### ISSUE THREAD

**Issue by NO-ob** [DS-Homebrew/TWiLightMenu#1523]
**Console Configuration:** Nintendo DSi with hiyaCFW + Unlaunch 
**TWiLight Menu++ Version:** v20.4.1
**TWiLight Menu++ Theme:** Nintendo DSi

### Expected behaviour

Touch to work because this is the recommended setting
"For best compat on flashcards please set to touch mode to DSi mode"

### Actual behaviour

When launching my acekard2i from the old ds menu and loading pokemon platinum pressing the touch screen will make audio turn off and also make the touch screen stop working. These both go away after restarting the console.

Reproducable on pokemon silver also
### Steps to reproduce

1. Boot ds into twilightmenu
2. Press select to get to ds menu
3. Launch slot1/flashcart
4. Load a game
5. Press touch screen

**Comment by RocketRobz** [comment]
Is Slot-1 SCFG access turned on or off?

**Comment by NO-ob** [comment]
off does it need to be on?

**Comment by RocketRobz** [comment]
It needs to be kept on for the feature to work properly.
If this bug still occurs, see if it also happens when the ROM is loaded from the console's SD card.

**Comment by NO-ob** [comment]
> It needs to be kept on for the feature to work properly.
> If this bug still occurs, see if it also happens when the ROM is loaded from the console's SD card.

Just tested It doesn't cause the sound/bottom screen crash with sd loading only when playing a slot-1 game. I tested with a real diamond cart instead of flash cart and that also has the crash

**Comment by RocketRobz** [comment]
That's expected with regular cartridges, since they only use DS touch mode.
On flashcards with SCFG access, nds-bootstrap is supposed to switch to DS touch mode, which is the case on my side, but isn't doing so on your side for some reason.
Download [this](https://github.com/TWLBot/Builds/commit/dbd20d747a721cb4230b70819b1f0a775d57e63c) nightly build of nds-bootstrap, and put it on both your flashcard and SD card.
After putting it on both cards, set `Bootstrap` to `Nightly` in the per-game settings menu for your game.

**Comment by NO-ob** [comment]
same thing happens with that after putting it onto the dsi sd, i'm not using twilight/bootsrap on the flashcart by the way i'm using akaio just using twilight as a menu replacement on the dsi

**Comment by RocketRobz** [comment]
Stick to using DS touch mode then.
