### ISSUE TITLE
Pokémon HeartGold (U) (Randomized) (IPKE) isn't detected as AP patched, crashes randomly 

### ISSUE THREAD

**Issue by barroer** [DS-Homebrew/TWiLightMenu#1541]
**Console Configuration:** New Nintendo 3DS XL with Luma3ds
**TWiLight Menu++ Version:** Stable TwilightMenu++ v.21.1.1
**TWiLight Menu++ Theme:** Original R4, default skin.

### Expected behaviour

The game should boot normally and without giving an Anti-Piracy Warning nor having random black screen crashes

### Actual behaviour

The game prompts an Anti-Piracy Warning upon trying to boot it, something that shouldn't happen as TwilightMenu++ has a built-in AP patch for Pokémon HeartGold (U) (Randomized) (IPKE). When I play it, it randomly crashes giving a black screen.

### Steps to reproduce

1. Get your Pokémon HeartGold (U) (Randomized) (IPKE) ROM and try to boot it, it should give you the Anti-Piracy warning.
2. Boot the game and play it for some time. After some time, the game should sometimes give you a black screen crash upon doing things such as entering houses and ending fights. It has happened twice in around 15 minutes of gameplay to me. I am not sure if this error should be posted here, but I think it may be.

**Comment by Squall-Leonhart** [comment]
Randomized roms must be AP patched prior to randomizing.

**Comment by Fackey** [comment]
I was able to patch Pokemon White (randomized) with the ips files that come with TM++. Haven't gotten cheats to work though.

**Comment by NightScript370** [comment]
TWiLight AP patching and cheats uses hashing, title IDs and other things to determine its status for each game. However, it cannot detect randomness.

If you have access to place these randomized ROMs in the first place, you probably also are able to change the order of how roms are on your SD card. AP patch is supposed to be applied first

Closing, due to the inability to solve.
