### ISSUE TITLE
DS rom titles appear corrupted

### ISSUE THREAD

**Issue by Arlisbloxer05** [DS-Homebrew/TWiLightMenu#1547]
**Console Configuration:** Nintendo DSi with Memory Pit + Unlaunch 
**TWiLight Menu++ Version:** 21.1.1
**TWiLight Menu++ Theme** Nintendo DSi + Dark Theme

### Expected behaviour

Titles on non-DSiWare roms should appear as they normally do in their respective languages.

### Actual behaviour

Titles appear as garbled text as seen [here](https://cdn.discordapp.com/attachments/715632911390474388/867224147851608064/20210720_215053.jpg), though they run just fine.

### Steps to reproduce

I unfortunately do not know how to reproduce this, as it just happened after 3 weeks of not using my DSi. I apologize for not being able to help provide steps.

**Comment by RocketRobz** [comment]
1. Change the Game Title Language in TWLMenu++ Settings to any setting that isn't `System`.
2. Which language is set in System Settings?

**Comment by Arlisbloxer05** [comment]
ah, the game title language was what caused it. weird.

**Comment by RocketRobz** [comment]
Can you tell me which language is set in System Settings (not TWLMenu++ Settings)?

**Comment by Epicpkmn11** [comment]
Was it changing the `Game Title Language` something that wasn't `System` that fixed it, or did you actually do something else like change the `Game Language` or set the `Game Title Language` *to* `System`?

I think I found the cause of this bug (see #1548) but what I found is caused by the Game Title Language *NOT* being system, so if that fixed it for you there's clearly some other bug I'm missing...
