### ISSUE TITLE
DSI wont load games

### ISSUE THREAD

**Issue by Mark-V-Laviathan** [DS-Homebrew/TWiLightMenu#162]
Im on the latest version and when i try to load games it is just a blanc white screen.

**Comment by andrescurto** [comment]
I have the same problem. Please check the following points to see if you have the same problem I have, since that way we might end up coming up with a solution.
• NDS Cartridges work fine (Try it only if you have any)
• Going into System Settings > Internet Settings > Nintendo DS Connections works fine
• DSiMenu++ gives you a white screen after you select "Start DSiMenu++" on the launcher
• Install NTR Launcher and insert an NDS cartridge on your 3DS, then boot NTR Launcher. It should give you a white screen. 

If you have all issues posted above that means you have the same problem I have and that, for some reason, NDS apps don't work

**Comment by NightYoshi370** [comment]
He is using a DSi, not a 3DS

**Comment by andrescurto** [comment]
I'm dumb. My brain just read 3DS for some reason

**Comment by Thundrakion** [comment]
Version 6.0 of DSiMenu++ seems to have similar issues on my DSi XL prior to updating Unlaunch to 1.3, but after that, it loads the rom and then freezes on a black screen, while cartridges freeze on a white screen and DSiWare reloads DSiMenu++.

**Comment by NightYoshi370** [comment]
@Mark-V-Laviathan you'll need to give us more information. Saying "It's just a white screen" won't help us. Please give us more information

**Comment by Aquamarino** [comment]
> Same for me
> 
> Just change nds-bootstraprelease.nds in _nds for this one older https://drive.google.com/open?id=1YApTs9kclwr3GcWSYpvxMYS078y9YRFO and nds games will load again

Useful!!! Thanks

**Comment by SimonBaars** [comment]
Did not work for me sadly. Whatever version of bootstrap I use, white screen after loading on any game/dsiware. TwiLightMenu itself works fully (except for touch screen). I boot without CFW using the bootcode.dsi. When on white screen, just the blue light (power) and yellow light (network) are burning. I tried about 5 different nds-bootstrap versions.
