### ISSUE TITLE
Autoboot fail on DSONE clone

### ISSUE THREAD

**Issue by koolok** [DS-Homebrew/TWiLightMenu#1628]
**Console Configuration:** DS Lite, DSONE clone (aliexpress)
**TWiLight Menu++ Version:** v21.5.1
**TWiLight Menu++ Theme:** Nintendo DSi

### Expected behaviour

Autoboot

### Actual behaviour

FAT init failed!

### Steps to reproduce

1. Format sd card using ubuntu `sudo mkdosfs /dev/mmcblk0p1 -F 32`
2. Install TWiLight Menu++ on a DSONE (work)
3. Put `SuperCard DSONE & SuperCard DSONEi` autoboot files on sd card root

If it can help, so far I'm using `RetroGameFan Multi Cart Update v7.06` and it works well, but `SuperCard_DSONE_EOS_sp6_20130129_5850fix` doesn't work.

I can boot using `BOOT.NDS` it's just the autostart that fail.

**Comment by lifehackerhansol** [comment]
On the note of EOS, you are not using the DSONE SDHC kernel, you’re using the original DSONE kernel. (In DS-Homebrew/flashcard-archive you’ll see the SDHC version which is what you need)

on to the autoboot. Do you have a 2GB SD to test by chance?

**Comment by koolok** [comment]
> On the note of EOS, you are not using the DSONE SDHC kernel, you’re using the original DSONE kernel. (In DS-

Homebrew/flashcard-archive you’ll see the SDHC version which is what you need)
My bad, I already tried `SuperCard_DSONE_SDHC_EOS_sp6_20121206` and it is staying forever on the loading screen.
 
> on to the autoboot. Do you have a 2GB SD to test by chance?

Arff no, I have a 16GB and a 128GB.

**Comment by lifehackerhansol** [comment]
Your DSONE SDHC has a defective PSRAM. You will not be able to use the EOS kernel. You _**should**_, in theory, be able to use both YSMenu and TWiLight Menu++, but we need to troubleshoot the latter.

I think I know what things to try here, but I'm a little hesitant to make a related pull request because I do not know how this would affect loading from the DSONE-not-SDHC. 

Could you perhaps join the Discord server linked on the main page of this repository for more direct support? I am going to leave this issue open but I'd like faster communication.

**Comment by koolok** [comment]
@lifehackerhansol gave me this TTMenu.DAT that fix the issue
[TTMENU.zip](https://github.com/DS-Homebrew/TWiLightMenu/files/7220749/TTMENU.zip)
 
Thank you lifehackerhansol, and all the contributors.

**Comment by lifehackerhansol** [comment]
I am going to leave this open for now until I think of a way to get around this for all other DSONE SDHCs. Theoretically, this should work for every one of them.
