### ISSUE TITLE
Slot 1 error

### ISSUE THREAD

**Issue by thenthjojo** [DS-Homebrew/TWiLightMenu#1633]
**Console Configuration:** New Nintendo 2DS version 11.13.0-45U with Luma 3DS.
**TWiLight Menu++ Version:** v21.5.1
**TWiLight Menu++ Theme:** Nintendo 3DS + Dark

### Expected behaviour

Last loaded game should boot up in Slot 1 while GBARunner2 should be an option in Slot 2.

### Actual behaviour

Slot 1 appears as an empty option with only "slot1" as the label, which takes me to a screen with 4 squares that alternate between red and green.  Recently appeared games are listed in Slot 2 and there is no option in the settings to reverse this behavior.  GBA games also show visual glitches.
When the setting to auto-load games in Slot 1 is enabled, the same thing happens and it causes a loop that I could not fix with reinstalling TWiLight Menu++.
### Steps to reproduce
Unknown.
![image](https://user-images.githubusercontent.com/34974321/134592342-87269a23-aba9-403b-aa75-4619f02915da.png)
![image](https://user-images.githubusercontent.com/34974321/134593124-24351505-daaa-4f75-9b95-befebdec31d4.png)

**Comment by RocketRobz** [comment]
1a. It makes more sense to have the Slot-1 game appear on the top, because in the original DS menu, it's shown on the top as well.
1b. TWiLight Menu++ isn't compatible with all flashcards. If it's a retail game though, make sure the cartridge is correctly inserted.
2. GBARunner2 being on the bottom was because back then, we couldn't pass arguments to it to run GBA ROMs. This is now the case in later versions, so keeping it in the DS Classic Menu would be pointless.
