### ISSUE TITLE
Hotkey option bugged

### ISSUE THREAD

**Issue by Kiraxxx25** [DS-Homebrew/TWiLightMenu#1649]
I’ve accidentally changed the hotkey button now I can’t play any game properly since the nds bootstrap menu pops up in game, i don’t know how to change or reset this setting, if anyone knows please help me.

**Comment by Epicpkmn11** [comment]
Simply hold the new combo you want when setting, then make sure to use <kbd>B</kbd> to exit TWiLight Menu++ settings so it saves instead of just rebooting. The default is <kbd>L</kbd> + <kbd>Down</kbd> + <kbd>SELECT</kbd> fyi.

Also if you've lost the setting it's on the Games and Apps settings page and like 2/3rds down iirc.

**Comment by Kiraxxx25** [comment]
Thank you so much!!! It solved the issue
