### ISSUE TITLE
Missing Settings on TWLMenu Settings

### ISSUE THREAD

**Issue by gyrorayo** [DS-Homebrew/TWiLightMenu#1702]
**Console Configuration: O3DS / Luma3DS v10.2.1
TWiLight Menu++ Version: v23.1.1
TWiLight Menu++ Theme: Homebrew launcher**

**### Expected behaviour**

Go to TWLMenu Settings (SELECT button) >Games and Apps settings > Option to change CPU Speed for DS games (nds-bootstrap) is missing, and it's needed because can't set this via in-game menu>Options.

**### Steps to reproduce**

Press SELECT on main screen> TWLMenu Settings>Games and Apps settings

**Comment by Epicpkmn11** [comment]
This was an intentional change due to it mainly just causing bugs to globally change those. If it's not shown in per-game settings then that's because it's [blacklisted](https://github.com/DS-Homebrew/TWiLightMenu/blob/master/universal/include/twlClockExcludeMap.h) from that option due to being known to cause major bugs.

**Comment by gyrorayo** [comment]
> This was an intentional change due to it mainly just causing bugs to globally change those. If it's not shown in per-game settings then that's because it's [blacklisted](https://github.com/DS-Homebrew/TWiLightMenu/blob/master/universal/include/twlClockExcludeMap.h) from that option due to being known to cause major bugs.
> 
> Edit: If you really want to you can set `IGNORE_BLACKLISTS` to `1` in your `sd:/_nds/TWiLightMenu/settings.ini`, however they're blacklisted for a reason so this isn't recommended unless you're okay with potentially breaking games.

Tried with IGNORE_BLACKLIST, still can't see the option in TWLMenu Settings. I used to have cpu speed set to 133 in order to avoid slowdowns in certain parts of Castlevania Order of Ecclesia.

Could it be possible to change cpu speed (from 64 to 133 mhz) from the nds-bootstrap.ini? 

[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 0
CACHE_FAT_TABLE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
CONSOLE_MODEL = 2
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SOUND_FREQ = 0
HOTKEY = 284
NDS_PATH = sd:/roms/nds/2809 - Castlevania - Order of Ecclesia (U)(Venom).nds
SAV_PATH = sd:/roms/nds/saves/2809 - Castlevania - Order of Ecclesia (U)(Venom).sav
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = -1
REGION = -1
DSI_MODE = 1
BOOST_CPU = 133
BOOST_VRAM = 0
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
SWI_HALT_HOOK = 1
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0

Thank you so much for the support.

**Comment by Epicpkmn11** [comment]
it still won't show in global settings, but it should be in per-game settings with that enabled

2021/11/28 18:05、gyrorayo ***@***.******@***.***>> のメッセージ:


This was an intentional change due to it mainly just causing bugs to globally change those. If it's not shown in per-game settings then that's because it's blacklisted<https://github.com/DS-Homebrew/TWiLightMenu/blob/master/universal/include/twlClockExcludeMap.h> from that option due to being known to cause major bugs.

Edit: If you really want to you can set IGNORE_BLACKLISTS to 1 in your sd:/_nds/TWiLightMenu/settings.ini, however they're blacklisted for a reason so this isn't recommended unless you're okay with potentially breaking games.

Tried with IGNORE_BLACKLIST, still can't see the option in TWLMenu Settings. I used to have cpu speed set to 133 in order to avoid slowdowns in certain parts of Castlevania Order of Ecclesia.

Could it be possible to change cpu speed (from 64 to 133 mhz) from the nds-bootstrap.ini?

[NDS-BOOTSTRAP]
DEBUG = 0
LOGGING = 0
CACHE_FAT_TABLE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
CONSOLE_MODEL = 2
PRECISE_VOLUME_CONTROL = 0
SDNAND = 0
MACRO_MODE = 0
SOUND_FREQ = 0
HOTKEY = 284
NDS_PATH = sd:/roms/nds/2809 - Castlevania - Order of Ecclesia (U)(Venom).nds
SAV_PATH = sd:/roms/nds/saves/2809 - Castlevania - Order of Ecclesia (U)(Venom).sav
RAM_DRIVE_PATH = sd:/null.img
GUI_LANGUAGE = en
LANGUAGE = -1
REGION = -1
DSI_MODE = 1
BOOST_CPU = 133
BOOST_VRAM = 0
CARD_READ_DMA = 1
ASYNC_CARD_READ = 0
SWI_HALT_HOOK = 1
EXTENDED_MEMORY = 0
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
FORCE_SLEEP_PATCH = 0

Thank you so much for the support.

**Comment by gyrorayo** [comment]
You mean, now I can change it in the in-game menu? (L+DOWN+SELECT); I can't seem to be able to change it, even after changing IGNORE_BLACKLIST to 1.

**Comment by Epicpkmn11** [comment]
no, you should be able to change it by pressing Y on it in TWiLight. Though if you set Run in to DSi Mode then you should be able to change it from L + Down + SELECT.

2021/11/28 18:12、gyrorayo ***@***.******@***.***>> のメッセージ:


You mean, now I can change it in the in-game menu? (L+DOWN+SELECT); I can't seem to be able to change it, even after changing IGNORE_BLACKLIST to 1.
