### ISSUE TITLE
title-exclusive cheat (for mods)

### ISSUE THREAD

**Issue by CaiMiao** [DS-Homebrew/TWiLightMenu#1793]
**Is your feature request related to a problem? Please describe.**
When you use `usrcheat.dat` it check against the CRC which prevents modified ROMs from using cheat without modifying it.  
To avoid editing cheat database everytime we can load a cheat sheet (maybe just use `cheat.xml` format?) seperate from the database, not checking CRC value and share same filename (without suffix) with ROM.

**Describe the solution you'd like**
- Have option to enable separate cheat loading
- Load `abc.cheat.xml` for `abc.rom`
- Ignore CRC check of the seperate database, or load the CRC-null (`00000000`) entry (if using `cheat.xml` format)
- maybe that's it?

(*Details can be discussed)

**Describe alternatives you've considered**
Just provide an option to ignore CRC check, only GAME ID check (but tells users you may load wrong cheat).

**Additional context**
nope

**Comment by Minionguyjpro** [comment]
I think i understand you. You mean that we need to select them from a ID/title so that we can use cheats with patched roms?

**Comment by Kaisaan** [comment]
There is in fact a maintainer. Please see DeadSkullzJr's database. There is a Discord Server linked in the [GBAtemp forum post](https://gbatemp.net/threads/deadskullzjrs-nds-i-cheat-databases.488711/) for cheat requests. It would much easier to keep all cheats as a single database/file so that everyone can easily access them. Closing.
