### ISSUE TITLE
Boot shortcut of launching Slot-1 game card

### ISSUE THREAD

**Issue by CaiMiao** [DS-Homebrew/TWiLightMenu#1817]
**Is your feature request related to a problem? Please describe.**
Launch Slot-1 game card while booting on demand.

**Describe the solution you'd like**
Pressing X while booting to launch s1 game card

**Describe alternatives you've considered**
other key combo whatever

**Additional context**
nope

**Comment by lifehackerhansol** [comment]
I'm really unsure what the use case for this would be. If this is related to using flashcards, just turn on Autostart Slot-1 and enjoy TWiLight with full access to all slots. If this is a game... why are you using TWiLight to launch it lol.

**Comment by CaiMiao** [comment]
> I'm really unsure what the use case for this would be.
When you have retail game cards and flashcards and you swap it often, that is the case

**Comment by lifehackerhansol** [comment]
Again, at that point have Auto-start Slot1 turned on. If it detects a flashcart it will launch it with your Slot-1 extension options, if it's a game it'll launch as a game. 

I should also note this would only make actual sense on a DSi since on a 3DS you'd have a separate icon for the cart anyway, and a DS Lite kind of needs a cart to do anything at all. And, the DSi already has Unlaunch, and honestly I think you're better off just setting a button shortcut to the game card from there instead.

**Comment by NightScript370** [comment]
As lifehacker said, there is no environment where you can launch TWiLight before launching a separate cart and have the cart contents not be twilight.

This doesn't have a practical use case except for laziness to change settings.
Closing.
