### ISSUE TITLE
How to know the versions of the bundled emulators ?

### ISSUE THREAD

**Issue by billyjoker** [DS-Homebrew/TWiLightMenu#1843]
I'd like to know a way to know the emulator version included with the bundle. I try to get the version of the GameYob emulator but the GameYob included menu just says "GameYob"

**Comment by lifehackerhansol** [comment]
Emulators are always the latest version, or the latest found version.

For example emulators like GameYob or S8DS are pulled directly from their GitHub releases. So check its source: https://github.com/Drenn1/GameYob

Otherwise we just put whatever we find that is the latest such as jEnesisDS pulled from the latest version off their website: http://www.workingdesign.de/projects/jenesisds.php

Things like this you kind of have to search for. We don't keep track, I don't think we will.

**Comment by spellboundtriangle** [comment]
> Emulators are always the latest version, or the latest found version.

*This isn't technically true for SNEmulDS atm, it uses a specific version of Coto's ongoing project. The build is a few months old now
