### ISSUE TITLE
Remove Auto-Created Rom Folders and Files

### ISSUE THREAD

**Issue by PandaPJYuri** [DS-Homebrew/TWiLightMenu#1934]
It really grinds my gears when my roms folder is artificially bloated after every update. I have no intention to ever run atari games or colecovision games so the folders just get manually deleted every single update. Not to mention that if I did want to play them, I would create my own folder for them, because I don't like the format of how they are created now either. What is even worse is the "Place Roms/Saves here" files as they are more difficult to find and delete and are also needless. I agree that these files might be good for a new user who doesn't know how to format their files, but as someone who does, it is incredibly annoying. Therefore, I would like you to consider removing these auto-created rom folders feature or if its possible, limit it to first time users. Maybe the folders are generated on first start up and then write a file somewhere and on future runs, it checks to see if the file is there, and if it is not, add the folders. I only want to see this added because you only need these folders once before you understand it and manually deleting them is just annoying.
Please and thank you.

**Comment by Allinxter** [comment]
You don't need to extract the `roms` folder for each update.
As stated on the[ TWiLight Menu++ updating instructions](https://wiki.ds-homebrew.com/twilightmenu/updating.html), the only files necessary for applying an update are the ones inside the `_nds` folder and `BOOT.NDS` (and `title` if you use hiyaCFW).

**Comment by RocketRobz** [comment]
Also, if you're using a 3DS with Universal-Updater, then it's an issue with that application, not TWLMenu++.

**Comment by Epicpkmn11** [comment]
Should I simply make Universal-Updater exclude that folder? Currently Universal-Updater simply extracts the whole 3DS zip to root, but I could change that if wanted.

There isn't exactly an easy way to make Universal-Updater extract that folder on first install but not on reinstall, I could add a prompt message to skip it but that's a bit annoying since you always have to click that then... Could also add a specific script  to create the roms folders I suppose.

Might not be a bad idea to make those be mkdir'd by TWiLight instead of in the 7z so that they can be created on first load and not after. Could maybe even store a 'roms folder version' in the ini so it could make new folders on updates that add them, but not remake the old ones.
