### ISSUE TITLE
Launching Twilight menu from the 3ds homebrew (.3dsx)

### ISSUE THREAD

**Issue by kevincrans** [DS-Homebrew/TWiLightMenu#1948]
**Is your feature request related to a problem? Please describe.**
It's sometimes annoying that you have to launch it via the DS internet settings or going out of userland.

**Describe the solution you'd like**
I'd like a .3dsx executable to launch via the 3ds homebrew launcher.

**Describe alternatives you've considered**
I can just inject the cia and revert to stock firmware, for an incompatible game, I even installed the open_agb_firm.firm.

**Additional context**
It's just about ease of access and to learn if it is even possible to go to DSi mode (or any mode/VC) from a 3dsx file.
Don't take it too seriously.

**Comment by lifehackerhansol** [comment]
You can't access DSi mode in an ARM11 userland exploit (except menuhax. But at the point you're using menuhax just use CFW). This has been attempted before, and if it worked then installing boot9strap would be easier than ever. It's functionally impossible without a DSi-mode exploit just like the DS Internet Settings you've described, since your access to ARM9 is locked. Even TWLoader didn't support this, and that was quite literally a 3DS-mode app. 

We can make a 3dsx wrapper, sure, but it would be useless without DSi-mode access, which would force you to use custom firmware anyway. TWiLight Menu++ is not designed for the 3DS, at a technical standpoint.

This is out of scope of TWiLight Menu++.

**Comment by kevincrans** [comment]
Thank you. I guess I just install it as a CIA, cause I'm uninstalling CFW and therefor I have to restore the internet settings.
