### ISSUE TITLE
AP-Patch not applying or not working on self-dumped rom

### ISSUE THREAD

**Issue by freundTech** [DS-Homebrew/TWiLightMenu#2021]
**Flashcard or Exploits?** b9s + Luma3DS 11.0
**Base Console:** Nintendo 3DS Firmware 11.15.0-47E

**TWiLight Menu++ Version:** 
**TWiLight Menu++ Theme:** Default

### Expected behaviour

Running my self-dumped Legend of Zelda: Spirit Tracks should work without problems due to the AP-Patch included in TWiLightMenu++ being applied.

### Actual behaviour

Some control elements don't show up due to the AP-Patch not being applied or not working

### Steps to reproduce

1. Insert LoZ: Spirit Tracks cartridge (NTR-BKIP-EUR)
2. Boot into GameMode9
3. Dump cartridge (non-trimmed)
4. Leave GameMode9
5. Eject cartridge
6. Copy SPIRITTRACKS_BKIP01_01.nds from gm9/out to roms/nds
7. Start the game through TWiLightMenu++

**Comment by RocketRobz** [comment]
Do other games with AP work fine? If so, then the included AP-patch is apparently broken.

**Comment by Epicpkmn11** [comment]
Maybe check a hash of your dump against no-intro's hashes, it's possible (either by bad contact or fake cart) that a self made dump can have issues, if it isn't good clean the contacts and try again.

**Comment by freundTech** [comment]
> Maybe check a hash of your dump against no-intro's hashes, it's possible (either by bad contact or fake cart) that a self made dump can have issues, if it isn't good clean the contacts and try again.

I just checked the hash and it matches `6663 - Legend of Zelda, The - Spirit Tracks (Europe) (En,Fr,De,Es,It) (Rev 1)` decrypted in no-intro's database (marked as not verified there, but I guess it's quite unlikely that two people get exactly the same wrong dump).

> Do other games with AP work fine? If so, then the included AP-patch is apparently broken.

I currently don't have another game that needs an AP patch here, so I can't currently test that.

**Comment by SNBeast** [comment]
> (marked as not verified there, but I guess it's quite unlikely that two people get exactly the same wrong dump)

This has nothing to do with nds-bootstrap, but if you could, please do submit your dump info to the dat-o-matic. It's marked as unverified, rather than trusted not verified, because the only available dump is from a scene group, and scene groups sometimes got things wrong in the dash to be first and from use of inaccurate tools (and sometimes from fixing AP themselves). It'd be nice to have confirmation that we have the right info.

**Comment by freundTech** [comment]
I just tried to manually patch it using DS-Scene Rom Tool and it's still not working. Do they use the same patch?

**Comment by SombrAbsol** [comment]
I also just came across this error, with the same game, region and revision.

Some additional details:
- AP activates during the train driving tutorial. It blocks all console button controls, hides and makes inaccessible the train controls on the touch screen. Only the movement of the camera with the touch screen is allowed.
- Since the controls are blocked, it is not possible to run away from the pig blocking the track, which blocks the train and prevents it from moving forward. The game is in a way softlocked.
- This code, present on the DeadSkullzJr cheat database, seems to correctly remove the AP from the game, thus solving the problem:

```
E23FC400 000000A0
E59D3000 E3530001
1A000002 E59F300C
E59F400C E5834000
E28DD02C E8BD8018
020C2594 EA0CE7A3
E3E01000 E92D0007
E59F0048 E5901000
E59F2048 E1510002
059F1044 05801000
059F1040 05801004
E59F002C E5901000
E1510002 059F1030
05801000 059F102C
05801004 E8BD0007
E1500001 E51F005C
E2800008 E12FFF10
020C200C 020C1F48
E92D47F8 E3A00001
E12FFF1E E3A00000
E12FFF1E 00000000
D2000000 00000000
5202DC58 E28DD02C
0202DC58 E51FF004
0202DC5C 023FC400
D2000000 00000000
```

With AP:
![senpai_converted_1667297811 1328716](https://user-images.githubusercontent.com/74314538/199211838-cb48d5d1-584f-4474-9816-c2f21337fa7e.png)

Without AP:
![senpai_converted_1667297861 3198018](https://user-images.githubusercontent.com/74314538/199211850-664a9550-d5cf-483a-b7f0-a2f420baae3f.png)


If necessary, here are three checksums of my Zelda Spirit Tracks (Europe) (Rev1) ROM:
- MD5: b822bc0934831e971c4ac2f8b1ab4194
- SHA-1: dcb221a89acb894503a461c2c7d4cfdad9a06b68
- SHA-256: b2bdc0ac110884ed8bca1326938523816926fbb905f1454e2bbfe6427cbfb18f

**Comment by RocketRobz** [comment]
Proper AP-fix of Zelda Spirit Tracks (Europe) (Rev 1) has been added as of later versions.
