### ISSUE TITLE
3DS（To switch the game）（soft reset）切换游戏不成功

### ISSUE THREAD

**Issue by AK580** [DS-Homebrew/TWiLightMenu#2052]
### Discussed in https://github.com/DS-Homebrew/TWiLightMenu/discussions/2051

<div type='discussions-op-text'>

<sup>Originally posted by **AK580** September 20, 2022</sup>
I have one N3dsll，
The TW++ is installed，
When I want to quit the NDSgame
I press the L+R+↓+B button，
TM++ Just shut it down，
Back to the main screen of 3DS，
Very few ROMs can be returned to the main screen of TM++，
It's a problem for me，
I don't know if it has anything to do with my use of Chinese-NDSrom,
Please help me.
</div>

**Comment by NightScript370** [comment]
This is more of a nds-bootstrap issue rather than one found in TWiLight Menu++. Either way, try letting us know in the DS(i) Mode Hacking discord server if the in-game-menu's reset game option works.
Link to that can be found in the readme.

Closing, but if you cannot access Discord, I'm keeping the Discussion open. Let's just keep it all there, though

**Comment by AK580** [comment]
Thank you for your reply.
I do not have access to Discord,
I'm going to try to get help with the NDS-Bootstrap project,
Thank you for your help.
