### ISSUE TITLE
Server/Private server selection.

### ISSUE THREAD

**Issue by EpicDoodleboy2** [DS-Homebrew/TWiLightMenu#2196]
**Is your feature request related to a problem? Please describe.**
Yes, when I use the dns server I use into my 3ds internet settings (I upgraded to a new 3ds xl) then it won't connect to nintendo network or pretendo network.

**Describe the solution you'd like**
Have a 'private server' option in TWL settings and has a selection of Wiimmfi ,New wfc or custom  (It allows you to name one and put in a dns entry)
And it would have a option For every game or one.

**Additional context**
Goes with https://github.com/DS-Homebrew/TWiLightMenu/issues/2110

**Comment by NightScript370** [comment]
With the exclusion of DSi-Mode based applications, 3DS configurations and DS configurations are separate. They each have their own 3 unique slots for their own supported configuration types. Thereby, the problem is invalid for everything that isn't excluded (99% of the library).
Furthermore, WiFi settings aren't something that TWiLight controls. Combined with the lack of overriding possibilities, this cannot be implemented in a comfortable way in terms of how it would point to nds-bootstrap (because the TWiLight side is easy).
