### ISSUE TITLE
Some Characters are been replaced and there are cases that some icons are sorted a wrong way.

### ISSUE THREAD

**Issue by t33st33r** [DS-Homebrew/TWiLightMenu#223]
A. When I navigate through my folders I see some characters are wrong. Please add unicode support.

B. Sometimes some folders precede the _"Back"_ one (you can see _"+"_ and after that one _"Back"_). A folder can be named _"Blank"_ but you cannot name it _".."_ so I suggest that name to be used as a name replacement for future versions. For more highlighting you can add an _arrow up_ to the icon (it is just a suggestion).

Thanks in advance for your great work. Your work makes me and my niece happy because now we can play videogames together =).

This is not my native language... excuse my low level english language please.

**Comment by NightYoshi370** [comment]
I'm not too sure that the second issue has been fixed, but has the unicode issue still been happening for you

**Comment by NightYoshi370** [comment]
Hey @t33st33r, can you download the latest commit and try to see if the bugs are fixed?

**Comment by chyyran** [comment]
Unicode support is only implemented for game title parsing in a very restricted manner due to RAM constraints. It only supports ASCII-Extended, as well as large and small variants for each of _hiragana_ and _katakana_ scripts as well as an assortment of unrelated kanji that was found in the DSi system menu font.

Because of the large varieties in file and folder naming, Unicode support was not implemented for file name parsing.
