### ISSUE TITLE
Feature to config WiFi settings in DS Lite / DS Fat

### ISSUE THREAD

**Issue by GorGylka** [DS-Homebrew/TWiLightMenu#2275]
Nintendo DS Lite and DS Fat does not have feature to config WiFi Network settings internaly. 
Luckily, games that use WiFi to play over the Internet have built in-game menu to set up WiFi. 
Is it possible to extract this part of code of the game, then pack again to .nds and add it as an additional item in the settings menu? thank you in advance.

**Comment by PW5190** [comment]
If you have a softmodded 3DS, you can dump the WFC Settings ROM from the NAND using GodMode9. The WFC Settings ROM has the title ID of `B88A` with the name `NINTENDO DSi™ Demonstration`, and its icon has "SDK" written in small print above the DS logo.

**Comment by Minionguyjpro** [comment]
No, someone would need to ADD this dump to TWLMenu. Or is this illegal?

Op ma 21 aug. 2023 02:27 schreef Elon ***@***.***>:

**Comment by RocketRobz** [comment]
> No, someone would need to ADD this dump to TWLMenu. Or is this illegal?

It is illegal, as the dump contains copyrighted content.

**Comment by PW5190** [comment]
> > No, someone would need to ADD this dump to TWLMenu. Or is this illegal?
> 
> It is illegal, as the dump contains copyrighted content.

I agree with Rocket Robz. The WFC Settings ROM is treated like a commercial game, and we all know it is illegal to pirate commercial material. If you want the WFC Settings ROM, you'll need a softmodded 3DS family system with GodMode9, and dump the ROM from the system's NAND. (As usual, I will not share any copyrighted material, since that is considered piracy in my book.) Case closed.
