### ISSUE TITLE
M3 DS Real Autoboot Breaks After RetroGameFan Multi Cart Update

### ISSUE THREAD

**Issue by crazyjat** [DS-Homebrew/TWiLightMenu#2355]
**Flashcard:** M3 DS Real 
**Base Console:** DS Lite

**TWiLight Menu++ Version:** 26.6.0
**TWiLight Menu++ Theme:** Nintendo DSi

### Expected behavior

M3 DS Real should be able to auto-boot into Twilight Menu with working "kernel" support.

### Actual behavior

M3 DS Real does NOT auto-boot into Twilight Menu with working "kernel" support after applying RetroGameFan Multi Cart Update 7.06 files.

### Steps to reproduce

1. Download latest twilight menu for flashcard and install as directed. 
2. Add Autoboot files.
3. SKIP Flashcart Loader files as they don't work with M3 DS Real.
4. Download RetroGameFan Multi Cart Update 7.06 and install "M3Real_M3iZero YSMenu" files to flash cart as well as supporting DAT files. 

### Notes

If step 4 is skipped, Twilight Menu auto-boots just fine, but won't play games using "kernel" set in settings, only with nds-bootstrap.

If step 4 is completed, YSMenu boots instead of Twilight Menu. Starting Twilight Menu from YSMenu with "kernel" set in settings, DS games run correctly.

**Comment by lifehackerhansol** [comment]
There's a reason why flashcart loader steps are _before_ autoboot; it's because of exactly what happens when you do step 4.

RetroGameFan's package conflicts with TWiLight Menu++'s autoboot, because the flashcart itself expects to boot from the files in the `system` folder. So you need to pick between the `system` folder from TWiLight or the `system` folder from YSMenu. Because of this, we let users install YSMenu _first_, so that in the event users aren't following the `DUAL BOOTING` instructions in RGF's thread, following the Autoboot steps from TWiLight right after this will make sure TWiLight's autoboot is the one being executed.
