### ISSUE TITLE
WFCReplay cheat freezes game when started

### ISSUE THREAD

**Issue by PkmnTrainerRed42** [DS-Homebrew/TWiLightMenu#638]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x] Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[v8.4.0]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [ ]  DSi Menu
- [x]  3DS HOME Menu
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behavior

1.wfc cheat gets turned on
2.game should start

### Actual behavior

the game doesn't start

### Steps to reproduce

1.have any game that supports the WFCReplay Code
2. Turn the code on
3. Start the game

**Comment by vaguerant** [comment]
This isn't an actual solution to the issue at hand, but the [nds-constraint](https://github.com/KaeruTeam/nds-constraint) exploit makes WfcReplay unnecessary on any up-to-date server. Nintendo's SSL code for DS is bugged and any server updated to support nds-constraint can fool the DS software into believing it has a signed certificate, so that patching games to use HTTP is no longer necessary.

**Comment by NightYoshi370** [comment]
This isn't a TWiLightMenu++ issue.
Please use the nds-bootstrap github repository for that
