### ISSUE TITLE
Add toy story 3 widescreen support

### ISSUE THREAD

**Issue by MDHEXT** [DS-Homebrew/TWiLightMenu#727]
Please add toy story 3 widescreen support, and fix the volume issue where the music is too low.
![1566002580272283935679719375494](https://user-images.githubusercontent.com/42657178/63204524-bf8db880-c055-11e9-995c-b40db1e86d7b.jpg)
![15660026168781951660849020531440](https://user-images.githubusercontent.com/42657178/63204529-ccaaa780-c055-11e9-941e-a019dfe10a87.jpg)

**Comment by NightYoshi370** [comment]
This is not something that TWiLightMenu++ handles. Please ask this on the Widescreen Cheat for 3DS GBATemp thread

**Comment by vaguerant** [comment]
This game is really not a good candidate for playing in widescreen on the 3DS. The gameplay is on the bottom screen and heavily uses stylus controls in gameplay. Currently we don't even have a way to swap screens, but even once we do, this game's reliance on touch input would make it unplayable with screens swapped.

Over in the GBATemp thread NightYoshi370 mentioned, I've posted a widescreen hack for it anyway in [this post](https://gbatemp.net/threads/widescreen-cheats-for-ds-games-on-3ds.543212/#post-8712884) (see "Bottom-screen games"), but this code will essentially only be useful for people playing the game in an emulator. It won't be added to TWLMenu++ because it's just not usable on real hardware.
