### ISSUE TITLE
GameYob Save creating issues

### ISSUE THREAD

**Issue by FlameKat53** [DS-Homebrew/TWiLightMenu#835]
- **Console Specifications:** DSi XL, Unlaunch without CFW, launching TWLMenu++ using Unlaunch keybinds
- **Code tested on:** Release v11.1.0
- **Theme Used:** DSi Theme

### Expected behavior

The game boy game should boot with a save file named `Legend of Zelda, The - Link's Awakening DX (USA, Europe) (SGB Enhanced) (GB Compatible).sav`

### Actual behavior

The game boy game boots and creates a save file named `Legend of Zelda, The - Link's Awakening DX (USA, Europe) (SGB Enhanced) (GB Compatible)@.sav`

### Steps to reproduce

1. Name a game boy color rom to `Legend of Zelda, The - Link's Awakening DX (USA, Europe) (SGB Enhanced) (GB Compatible).gbc`
2. Launch the rom using TWLMenu++
3. You will have no save files in Link's Awakening

### Additional Information:
Using the same rom named `Link's Awakening DX.gbc`, the issue does not happen.
Launching GameYob.nds with GM9i, then starting the rom uses `Legend of Zelda, The - Link's Awakening DX (USA, Europe) (SGB Enhanced) (GB Compatible).sav`
The first launch of the game results in a white screen if the save did not exist prior to the first launch. Second launch works fine though.

### ROM Info
**MD5:** `8B9741F02B42CF20614A64F36D89D7A5`
**SHA1:** 088026C043E5BCDE30A685DC51F390E90B712211
**SHA-256:** 40B51E01D25CAE211D5540C4A92B62E94E6E786815AACD4707A59E209ADB1F1B

Also, here's the [blank save file](https://github.com/DS-Homebrew/TWiLightMenu/files/3957544/savefile.zip) it made

**Comment by SleepyLark** [comment]
Could it be because the file name is too long?

**Comment by Summerslyb** [comment]
I think it may related to too long fullPath (path+filename). 

In my experiments, the max len for loading is 112byte. (Otherwise, white screen or red crash)
For example: `sd:\roms\gb\Pokemon\Pokemon - Yellow Version - Special Pikachu Edition (USA, Europe) (GBC,SGB Enhanced)(8Mb)1.gb` (112byte)

However, the max len for saving is 102byte. (Otherwise, with a '@' in sav file)
For example: `sd:\roms\gb\Pokemon\Pokemon - Yellow Version - Special Pikachu Edition (USA, Europe) (GBC,SGB Enhan.gb` (102byte)

Very strange length limit. I think the main issue may related to old libfat.
Because the max len in gameyob is 256(MAX_FILENAME_LEN) in [io.h](https://github.com/RocketRobz/GameYob/blob/master/platform/common/include/io.h).
