### ISSUE TITLE
Tip for Wiki regarding macOS

### ISSUE THREAD

**Issue by gingerbeardman** [DS-Homebrew/TWiLightMenu#862]
https://github.com/DS-Homebrew/TWiLightMenu/wiki/How-to-update-TWiLight-Menu

> Be careful if you're on macOS, as it'll delete the folders, instead of merging them.

MacOS users can hold the Option key when copying folders to get the option to Merge.

![Screen shot 2020-01-11 at 11 28 57](https://user-images.githubusercontent.com/49612/72203601-9555f080-3465-11ea-96f0-a7213caed127.png)

**Comment by Epicpkmn11** [comment]
I've had that option delete folders in the destination before (10.13 iirc), maybe that was just a one time bug though...

**Comment by gingerbeardman** [comment]
I think it's not worth spreading FUD over this time-tested feature @Epicpkmn11

**Comment by Epicpkmn11** [comment]
Ah, Merge was default on my 10.14 computer as long as it was doing a copy, not a move, and does seem to be working correctly, I can't get it to merge on my iBook G4 with 10.5 that I use more, only overwrite, but that's pretty uncommon so I guess yeah that warning should probably be updated... I've just been kinda scared of the option since it failed on me in the past 😅

**Comment by gingerbeardman** [comment]
Works for me.

I do this way of merging every time I update and it's never gone wrong.

One thing to note, is that if the directories involve no new files (so they are exact matches in terms of number of files and names) then merge will never appear as replace is the only valid option at for that type of operation. Not an issue when updating TWLM+ though.

**Comment by NightYoshi370** [comment]
There we go, added it. This can be closed now
