### ISSUE TITLE
Have option to switch Slot-2 spot between "Last Ran ROM" and GBARunner2 in DS Classic Menu

### ISSUE THREAD

**Issue by SleepyLark** [DS-Homebrew/TWiLightMenu#945]
**Is your feature request related to a problem? Please describe.**
I've noticed that some users have been confused why GBARunner2 isn't in the Slot-2 spot anymore.  Personally I like having the "Last Ran ROM" in that spot as I can easily launch cartridge, but at the same time it made since that GBARunner2 was there since it was for GBA games

**Describe the solution you'd considered**
Having an option in the settings to switch between the old layout (GBARunner2 in Slot-2) and the new layout (Last Ran ROM in Slot-2).  You can even take it a step further and have an option to switch the Slot-1 spot between booting a cartridge and "Last Ran ROM" but would need a way to prevent the user from having both slots be Last Ran ROM as that would be redundant.

**Describe alternatives you've considered**
Not changing anything and remind people it's possible to launch .gba files through TWiLight Menu now.

**Comment by NightYoshi370** [comment]
> Not changing anything and remind people it's possible to launch .gba files through TWiLight Menu now.
This would be better approach in my opinion.

If we add it back, why would we keep it GBARunner2 exclusive? Why wouldn't we add nesDS or GameYob? Then, once we see the problem there, we run into another problem; Genesis and SNES don't function like that. They HAVE to be loaded through our menu so that they can be built. Then it'd be inconsistent, since we wouldn't have the other emulators.

That's why I don't think it should be added, but it's up to Robz

**Comment by Epicpkmn11** [comment]
> If we add it back, why would we keep it GBARunner2 exclusive?

If something like that were to come back, I'd say pinning a single app to show there would be the best, then people could pin GBARunner2, but also anything else if there's one app they want to have on quick access

**Comment by cyruzwings** [comment]
GBA game now can run directly from menu, just point to where you place GBA games and it launched GbaRunner2 automatically (try on TWiLightMenu v12.2.1).
Last ran ROM will show GBA if you play GBA before.
