### ISSUE TITLE
Touch screen not working 

### ISSUE THREAD

**Issue by bigpeenboy** [DS-Homebrew/TWiLightMenu#972]
when I launch a game on twilight menu the touch screen doesn’t work with twilight menu but works with everything on my console for example when I play mario maker 3ds the touchscreen works but when I boot up a game like super Mario 64 on twilight menu the touch screen doesn’t  work what should I do help me please

**Comment by RocketRobz** [comment]
Update nds-bootstrap.

**Comment by Galenmacil** [comment]
I can confirm this problem.

Running Twilight Menu++ latest release and NDS-Boot 0.31.0 via UnLaunch.

### Hardware:
DSi with Nintendo Firmware 1.4.4u. 1 GB SD card (FAT partition) in DSi SD slot. Nothing in Slot-1.

### Problem:
Launching any homebrew application (in .NDS format) via TwilightMenu++ result in the touch screen not responding at all.

Tested this with several homebrew games and applications including: BS Chess, Crawl DS, Dice Roller DS, Every ExtendDS, Glubies Planet, GO Life, Mastermind DS, Nethack DS, NitroTracker, Pocket Physics, Powder, Rogue DS, Virtual Tower Defense DS, World of Sand.

**Note that DSiWare Apps are working just fine.**

### Partial Workaround
The only partial workaround I found is to set Twilight Menu++ setting under "Games and Apps settings" entry "Run in" to "DS mode".

I say partial workaround because while this fix the touch screen, other weird things are still plaguing homebrew apps launched in via Twilight Menu++: Extremely slow loading time for some of them, if they load at all, and there is this strange issue with "World of Sand" where, on the touch screen, that is now working in DS mode, only about 3/4 of the screen are used as if the bottom LCD coordinate are shifted somehow causing the bottom 1/4 part to behave strangely. 

### Food for thoughts
After many hours of testing various settings, I believe that TwilightMenu++ somehow detect when an application is an homebrew an use "nds-boostrap-hb-release.nds" instead of "nds-bootstrap-release.nds". I tried to copy and rename the non homebrew bootstrap to fool TwilightMenu++ into using the regular one instead but it simply do not work.

Could the problem be in the "hb" bootstrap .NDS variant?

**Comment by RocketRobz** [comment]
nds-bootstrap is supposed to switch the touch mode to NTR, thus making touch work in those homebrew apps.
Make sure direct boot is turned off in the per-game settings.

Also, you should check if touch works in GBARunner2 by touching the touch screen during gameplay.

**Comment by Galenmacil** [comment]
I tried setting "Slot-1 launch method" to "Reboot" instead of "Direct" (which seems to be the setting you suggested in your comment). Makes no difference... Isn't it supposed to be for Slot-1 booting behaviors only?

Also, and I recheck right now to be sure, GBARunner2 touch screen functionalities are working properly weither the setting "Run in" is set to "DSI", "DS" or "DSI (forced).

**Comment by midbus** [comment]
having a similar issue after updating nds-bootstrap. Touch Screen works on 3DS, works on DSiWare, and even works when given the 'touch the screen' prompt from Twilight Menu. Once into the menu proper, nothing touch screen works, and when loading DS games the touch screen still fails.

**Comment by RocketRobz** [comment]
@midbus Make sure DS mode is set in TWLMenu++ Settings.
Also, delete the TWLMenu++ titles in FBI, then install the latest CIAs.

**Comment by Galenmacil** [comment]
So, final report on this subject from what I have learned, in case this can help others. Note that I tested this on a DSi:

1 - The answer to most homebrew applications no loading or loading but with a disabled touch screen is simple: Y. As in press "Y" when highlighting a title to get to the "per apps settings" page.

2 - Most homebrew applications/games should be run in "DS" mode. This will likely fix touch screen not responding issues.

3 - If an applications/games requires some sort of file reading/writing from the FAT file system on the SD card, one should put the game to run with "Direct boot: No" This will most likely fix loading and saving problems.
One particular case where I actually had to put this to "Yes" was with "World of Sand" otherwise, the bottom screen is not behaving correctly.

4 - From the test I ran, most app should have no problem running with the ARM9 at 133mhz. Might not be useful for less demanding ones but for others, namely physics or AI processing, you get a very nice speed boost.

5- "VRAM boost: On" caused some issue for me in Vector Tower Defense DS where the screen would not draw anything once in game. Probably best to leave it off.

The only option I am not fully understanding is  "RAM disk". Only available when "Direct boot" is set to no. 

As a new comer to TwilightMenu++, I could have used some sort of instructions manual or readme file to explain the basics. Would have saved a lot of time, albeit, in the current world situation, I do have plenty of free time available...
